PY_TB_VHDL = [ "util_unsynth.vhd", "mult_tb.vhd" ]
OPT_EFFORT_PHYS = 0
PY_DESIGN_VHDL = [ "mult.vhd" ]
USER_TOOL_FLAGS = 
PART = 10M08SAE144C8G
DESIGN_ARCH = main
SH_FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm-enc /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/maxv
RUN_SHIM = True
FREQ_MIN = 50
SIM_TOOL = MODELSIM

ECE327 = /home/ece327
SH_TB_VHDL = util_unsynth.vhd mult_tb.vhd
TB_ENTITY = mult_tb
GOAL_FREQ = 50
GOAL_PERIOD = 20
PRECISION_PART = 10M08SAE144C8GES
RPT_DIR = RPT
PY_FAB_SIM_LIBS = [ "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm-enc", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/maxv" ]
TCL_FAB_SIM_LIBS = { /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm-enc /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/maxv }
LOGIC_SYNTH_TOOL = PRECISION_RTL
TB_ARCH = main
TCL_TB_VHDL = { util_unsynth.vhd mult_tb.vhd }
GUI_FLAG = -shell
NUM_TIMING_PATHS = 5
PWR_TOOL = QUARTUS
INTERACTIVE_FLAG = False
BOARD = lstep
OPT_EFFORT_LOGIC_1 = 0
OPT_EFFORT_LOGIC_2 = 0
DESIGN_ENTITY = mult
FAMILY_SHORT = Max10
SH_DESIGN_VHDL = mult.vhd
ASIC = False
LC_FAMILY_SHORT = max10
OPT_EFFORT = 0
GENERICS = {  }
LIB_VHDL = util.vhd
SH_LIB_VHDL = util.vhd
USE_GUI = False
TB_VHDL = util_unsynth.vhd, mult_tb.vhd
SIM_SCRIPT = mult_tb.sim
FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm-enc, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/maxv
LOGIC_SYNTH_EXT = vhd
RPT_TDIR = RPT
FAMILY_LONG = Max 10
TCL_DESIGN_VHDL = { mult.vhd }
SPEED = 8
UWP = mult
OLD_DC_SHELL = False
PHYS_SYNTH_TOOL = QUARTUS
PROG = uw-synth
TCL_LIB_VHDL = { util.vhd }
DESIGN_VHDL = mult.vhd
PY_LIB_VHDL = [ "util.vhd" ]
